#!/usr/bin/perl
use strict;
use warnings;
use POSIX qw(strftime);


my @inputs;

my $makefile = "Makefile";
open my $fh, '<', $makefile or die "Cannot open file : $_"; #file handler
use Data::Dumper;


while(my $line = <$fh>){
  chomp $line; #gets rid of whitespace
  push(@inputs, $line);
}

sub parse_dep ($) {
   my ($line) = @_;
    return undef unless $line =~ m/^(\S+)\s*:\s*(.*?)\s*$/;
    my ($target, $dependency) = ($1, $2);
    my @dependencies = split m/\s+/, $dependency;
    return $target, \@dependencies;
}

sub mtime ($) {
   my ($filename) = @_;
   my @stat = stat $filename;
   return @stat ? $stat[9] : undef;
}

sub fileinfo ($) {
   my ($filename) = @_;
   my $mtime = mtime $filename;
   print "$filename: ";
   if (defined $mtime) {print strftime "%c\n", localtime $mtime}
                  else {print "$!\n"}
   return $mtime;
}

my %graph;
my %comgraph;
my @commands;
my $tar;
my $com;

for my $input (@inputs) {
  my ($target, $deps) = parse_dep $input;
  if(defined $target){
      $graph{$target} = $deps;
      $tar = $target;
    }else{
      if($input=~ "\t"){
        $input =~ s/\t|\n//g;
        $com = $input;
        push @{$comgraph{$tar}} , $com;
      }
    }
}

#if '@' in command then remove and call system,
#else print command and call system
foreach my $key (keys %graph){
  my @deps = @{$graph{$key}};
  foreach my $deps (@deps){
    print "$deps\n";
  }
}

print Dumper (\%graph);
