#!/usr/bin/perl
use strict;
use warnings;

my @inputs;

my $makefile = "Makefile";
open my $fh, '<', $makefile or die "Cannot open file : $_"; #file handler
use Data::Dumper;


while(my $line = <$fh>){
  chomp $line; #gets rid of whitespace
  push(@inputs, $line);
}

sub parse_dep ($) {
   my ($line) = @_;
    return undef unless $line =~ m/^(\S+)\s*:\s*(.*?)\s*$/;
    my ($target, $dependency) = ($1, $2);
    my @dependencies = split m/\s+/, $dependency;
    return $target, \@dependencies;
}


my %graph;
my %comgraph;
my @commands;
my $tar;
my $com;

for my $input (@inputs) {
  my ($target, $deps) = parse_dep $input;

  if(defined $target){
      $graph{$target} = $deps;
      $tar = $target;
    }else{
      if($input=~ "\t"){
        $input =~ s/\t|\n//g;
        $com = $input;
        push @{$comgraph{$tar}} , $com;
      }
    }
}

#if '@' in command then remove and call system,
#else print command and call system
foreach my $key (keys %comgraph){

  print "$key\n";
  my $string = "@{$comgraph{$key}}";
  my $firstchar = substr($string, 0,1);
  if($firstchar =~ "@"){
    system (substr($string, 1));
  }else{
    print "@{$comgraph{$key}}\n";
    system (@{$comgraph{$key}});
  }
}



print Dumper(\%comgraph);
